apiVersion: gcp-haiilo.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-gcp-haiilo
spec:
  projectID: test-dev-c391
  credentials:
    source: Secret
    secretRef:
      name: gcp-creds
      namespace: crossplane-system
      key: creds
