apiVersion: storage.gcp-haiilo.upbound.io/v1alpha1
kind: TransferJob
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/transferjob
  labels:
    testing.upbound.io/example-name: s3-bucket-nightly-backup
  name: s3-bucket-nightly-backup
spec:
  forProvider:
    description: Nightly backup of S3 bucket
    notificationConfig:
    - eventTypes:
      - TRANSFER_OPERATION_SUCCESS
      - TRANSFER_OPERATION_FAILED
      payloadFormat: JSON
      pubsubTopic: ${google_pubsub_topic.topic.id}
    project: ${var.project}
    schedule:
    - repeatInterval: 604800s
      scheduleEndDate:
      - day: 15
        month: 1
        year: 2019
      scheduleStartDate:
      - day: 1
        month: 10
        year: 2018
      startTimeOfDay:
      - hours: 23
        minutes: 30
        nanos: 0
        seconds: 0
    transferSpec:
    - awsS3DataSource:
      - awsAccessKey:
        - accessKeyIdSecretRef:
            key: example-key
            name: example-secret
            namespace: upbound-system
          secretAccessKeySecretRef:
            key: example-key
            name: example-secret
            namespace: upbound-system
        bucketName: ${var.aws_s3_bucket}
      gcsDataSink:
      - bucketName: ${google_storage_bucket.s3-backup-bucket.name}
        path: foo/bar/
      objectConditions:
      - excludePrefixes:
        - requests.gz
        maxTimeElapsedSinceLastModification: 600s
      transferOptions:
      - deleteObjectsUniqueInSink: false

---

